# Generated by Django 3.2 on 2024-05-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(verbose_name='Полный URL')),
                ('uniq_id', models.CharField(max_length=200, verbose_name='Уникальный идентификатор')),
            ],
        ),
    ]
