version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: toomike/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media

  frontend:
    image: toomike/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: toomike/foodgram_nginx
    depends_on:
      - backend
    ports:
      - "10000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/media
      - static:/backend_static
