# Generated by Django 3.2 on 2024-05-13 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Избранные рецепты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients_recipes', to='recipes.Ingredient', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shopping_list',
            field=models.ManyToManyField(related_name='shopping_list_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок'),
        ),
    ]
