# Generated by Django 3.2 on 2024-05-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_foodgramuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(default='media/avatars/avatar-icon.png', upload_to='media/avatars', verbose_name='avatar'),
        ),
    ]
