# Generated by Django 3.2 on 2024-05-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240525_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='subscriptions',
        ),
    ]
