# Generated by Django 3.2 on 2024-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_foodgramuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(default='media/users/avatar-icon.png', upload_to='media/users', verbose_name='avatar'),
        ),
    ]
