# Generated by Django 3.2 on 2024-05-26 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_foodgramuser_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodgramuser',
            name='subscriptions',
            field=models.ManyToManyField(related_name='user', through='users.UserSubscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
