# Generated by Django 3.2 on 2024-05-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_foodgramuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users', verbose_name='avatar'),
        ),
    ]
