# Generated by Django 3.2 on 2024-05-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_foodgramuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('id',)},
        ),
    ]
